#!/bin/sh

if [ "$#" -eq 2 ]; then
	if [ "$1" = "vol" ]; then
		# Arbitrary but unique message id
		msgId="991049"

		# Change the volume using alsa(might differ if you use pulseaudio)
		case "$2" in
			-d)
				amixer -q sset Master 5%-;;
			-i)
				amixer -q sset Master 5%+;;
			-t)
				amixer -q sset Master toggle;;
		esac

		# Query amixer for the current volume and whether or not the speaker is muted
		volume="$(amixer sget Master | tail -1 | awk '{print $5}' | sed 's/[^0-9]*//g')"
		mute=$(amixer sget Master | tail -1 | awk '{print $6}' | sed 's/[^a-z]*//g')
		if [ "$volume" = "0" ] || [ "$mute" = "off" ]; then
			# Show the sound muted notification
			dunstify -a "Volume" -u low -i audio-volume-muted-blocking -r "$msgId" "Muted" 
		else
			# Show the volume notification
			dunstify -a "Volume" -u low -i audio-volume-high -r "$msgId" \
			-h int:value:"$volume" " ${volume}%"
		fi
	elif [ "$1" = "bl" ]; then
		# Arbitrary but unique message id
		msgId="991045"

		# Change the volume using alsa(might differ if you use pulseaudio)
		case "$2" in
			-d)
				xbacklight -dec 5;;
			-i)
				xbacklight -inc 5;;
		esac

		# Query amixer for the current volume and whether or not the speaker is muted
		blight="$(xbacklight -get)"
		dunstify -a "Brightness" -u low -i brightness-display-symbolic -r "$msgId" \
		-h int:value:"$blight" "${blight}%"
	fi
fi
